name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Merge PDF
        run: node script.js
      - uses: actions/upload-artifact@v2
        with:
          name: merged
          path: ./merged.pdf
