name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Merge PDF
        run: node script.js
      - name: Add File
        run: |
          git add .
          git commit -m "merged pdf"
          git push
